### ISSUE TITLE
Suggestion: "Activate in table" setting

### ISSUE THREAD

**Issue by jms1voalte** [jrymk/restore-tab-key#14]
I normally type out tables by hand, with the pipe characters lined up so they "look right" in the markdown source as well as the rendered output. I use the TAB key to space things out for this.

I have to turn *off* the "Only activate in code blocks" setting for this, but this also disables the TAB key's functionality when typing bulleted lists (where I *want* the TAB key to indent the whole line rather than adding spaces or a TAB character).

It might make sense to offer separate toggles for different "typing states", such as ...

* Enable within code blocks
* Enable within a table
* Enable within a list
* Enable in all other cases

I *personally* would use "yes, yes, no, no" for these, but I can see where others might want different settings, especially if they're using other plugins that I don't use (or have never heard of).

**Comment by jrymk** [comment]
Great suggestion, also allows the hacky way of detecting lists with the exception regex. The table detection will still be detecting if the "|" character is in the beginning of the line (or else you have to finish the entire table structure in Markdown before taking effect)
![image](https://github.com/user-attachments/assets/69a1769b-cbf0-49b6-85a7-4067e7ea4861)

**Comment by jms1voalte** [comment]
That's *beautiful*.

One thing to mention as you write the regex'es, tables can be indented. This means that the first `|` on the line *can* have whitespace in front of it, so you'll want to use something like `/^\s*|/`. (Sorry if this seems really basic. At `$DAYJOB` I have to point out things like this all the time so, after ten-plus years it's kinda second nature to me.)

**Comment by jrymk** [comment]
Yep, although I don't know who would add a space before a table...
You apparently can not indent tables, so only white spaces are allowed before the pipe character, so `RegExp(`^ *\\|`, "u")` is what I ended up using.
Also, I fixed a quite serious bug too in 1.18.4.
Thanks!

**Comment by jms1voalte** [comment]
I do it all the time in the documentation I write for work ... [Marked2](https://marked2app.com/) supports it and shows the table indented as expected ... and [mdbook](https://rust-lang.github.io/mdBook/) shows the table but it's centered on the page so you can't really tell if it's indented correctly. (I keep meaning to edit the stylesheets and make it *not* center tables, but I haven't had time.)

I just tried it in an Obsidian note, apparently for the first time ever. Obsidian's markdown rendering engine *sees* the table but doesn't know how to render it. I tried a simple table, indented four spaces to match a list element above it. The only thing Obsidian shows is a small horizontal line for each row below the `|:-----|:-----|` row. I'll be reporting this as a bug in Obsidian (which I'm sure will be answered with five different "this plugin fixes that" responses).

Anyway ... thanks for looking at this, much appreciated.

**Comment by jrymk** [comment]
I really doubt Obsidian is going to fix it though 
https://forum.obsidian.md/t/cannot-indent-tables/74705
Obsidian's philosophy on the Markdown stuff seems to be "bare minimum to spec" and no fancy custom formatting available in some specific editor.
Obsidian ditches tab insertion and opts for indentation, which kinda makes sense, because you really can't do much with tabs in Markdown, except in the source view. But another important feature in Markdown is the code blocks (like MS Office Word doesn't have a code block, so that must say something to the position of MD (being a quick documentation tool for programmers?)) and it doesn't tab in the code blocks. This seems to be the main usage of tabbing in Obsidian, and I don't think Obsidian is going to change this as well, although aligning tab pipes with tab in the source view is a great used case too.
I don't really use Obsidian much TBH, it just doesn't feel that "comfortable" to use to me.

**Comment by jms1voalte** [comment]
Thanks for pointing me to that thread, it made me look a bit more closely at what was happenening and I noticed a bug that I hadn't noticed, because I didn't realize Obsidian's renderer requires a blank line above the beginning of a table.

[Here](https://forum.obsidian.md/t/indented-tables-are-rendered-one-column-off/86001) is that bug, if you're curious.
